# Summary: Oracle Gap Ratios Across 50 States (Employed Only)

Full 4-feature model: AGEP, SCHL, MARC, RELPC
(WKHP excluded — used in employed_only filter, mechanical relationship with log-income)

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 60)
pd.set_option('display.float_format', '{:.4f}'.format)

## Sex (Male / Female)

In [2]:
df_sex = pd.read_csv('../oracle_gap_scan_sex_employed.csv')
full_sex = df_sex[df_sex['n_features'] == 4].copy()
full_sex = full_sex.sort_values('gap_ratio_g0_g1', ascending=False)

# Rename for display
disp_sex = full_sex[['state', 'baseline_g0', 'baseline_g1', 'oracle_g0', 'oracle_g1', 'gap_g0', 'gap_g1', 'gap_ratio_g0_g1']].copy()
disp_sex.columns = ['State', 'Baseline(M)', 'Baseline(F)', 'Oracle(M)', 'Oracle(F)', 'Gap(M)', 'Gap(F)', 'Ratio(M/F)']
disp_sex = disp_sex.reset_index(drop=True)
disp_sex

,State,Baseline(M),Baseline(F),Oracle(M),Oracle(F),Gap(M),Gap(F),Ratio(M/F)
0,NH,0.7283,0.6892,0.6007,0.6075,0.1276,0.0817,1.5613
1,NV,0.7732,0.6767,0.6676,0.6040,0.1056,0.0727,1.4524
2,HI,0.7268,0.6549,0.6395,0.5925,0.0873,0.0625,1.3972
3,CT,0.8672,0.7137,0.7243,0.6108,0.1430,0.1029,1.3889
4,GA,0.8196,0.7349,0.6817,0.6315,0.1379,0.1033,1.3343
5,VA,0.8314,0.7457,0.6756,0.6264,0.1558,0.1193,1.3055
6,FL,0.8305,0.7008,0.7136,0.6108,0.1169,0.0899,1.3001
7,AZ,0.7729,0.6841,0.6561,0.5936,0.1168,0.0905,1.2904
8,NC,0.8057,0.7036,0.6818,0.6069,0.1239,0.0967,1.2815
9,AR,0.7308,0.6564,0.6283,0.5755,0.1025,0.0809,1.2666
10,SC,0.7871,0.6829,0.6637,0.5855,0.1233,0.0974,1.2663
11,MA,0.8002,0.7100,0.6730,0.6081,0.1272,0.1019,1.2486
12,TN,0.7852,0.6874,0.6621,0.5887,0.1231,0.0987,1.2467
13,NJ,0.8461,0.7461,0.7069,0.6331,0.1393,0.1130,1.2325
14,AL,0.7806,0.6783,0.6536,0.5746,0.1270,0.1038,1.2239
15,CA,0.8565,0.7878,0.7141,0.6711,0.1424,0.1167,1.2200
16,OR,0.7707,0.7102,0.6571,0.6167,0.1136,0.0936,1.2140
17,MD,0.8138,0.7468,0.6705,0.6285,0.1433,0.1183,1.2115
18,NY,0.8397,0.7334,0.7269,0.6402,0.1128,0.0932,1.2107
19,NM,0.8175,0.7416,0.6897,0.6351,0.1279,0.1065,1.2007
20,WA,0.7727,0.7218,0.6611,0.6277,0.1116,0.0941,1.1860
21,CO,0.7909,0.7070,0.6846,0.6168,0.1063,0.0902,1.1782
22,TX,0.8427,0.7480,0.7110,0.6355,0.1317,0.1125,1.1712
23,IL,0.7953,0.7179,0.6763,0.6152,0.1190,0.1026,1.1599
24,UT,0.7567,0.7489,0.6230,0.6325,0.1337,0.1164,1.1488
25,MN,0.7394,0.6796,0.6584,0.6089,0.0810,0.0706,1.1473
26,SD,0.7919,0.6429,0.7268,0.5860,0.0651,0.0568,1.1451
27,MO,0.7757,0.6790,0.6721,0.5881,0.1035,0.0909,1.1390
28,RI,0.7275,0.6425,0.6094,0.5385,0.1181,0.1040,1.1359
29,KY,0.7559,0.6763,0.6453,0.5789,0.1106,0.0974,1.1354
30,ID,0.7641,0.7128,0.6715,0.6312,0.0926,0.0816,1.1350
31,LA,0.8008,0.6998,0.6855,0.5973,0.1154,0.1025,1.1252
32,MI,0.7845,0.6753,0.6708,0.5743,0.1137,0.1010,1.1251
33,MS,0.7404,0.6613,0.6289,0.5595,0.1115,0.1018,1.0954
34,OH,0.7259,0.6637,0.6134,0.5606,0.1126,0.1031,1.0924
35,DE,0.7720,0.7283,0.6514,0.6178,0.1205,0.1106,1.0901
36,OK,0.7714,0.6906,0.6775,0.6033,0.0939,0.0873,1.0755
37,ME,0.6575,0.6463,0.5672,0.5611,0.0903,0.0852,1.0602
38,PA,0.7492,0.6832,0.6462,0.5851,0.1030,0.0981,1.0497
39,NE,0.7361,0.6572,0.6594,0.5823,0.0768,0.0748,1.0255
40,KS,0.7659,0.7077,0.6700,0.6135,0.0959,0.0941,1.0190
41,IN,0.7192,0.6480,0.6238,0.5543,0.0954,0.0937,1.0187
42,VT,0.6991,0.6815,0.6305,0.6129,0.0686,0.0686,0.9996
43,WI,0.7222,0.6423,0.6472,0.5644,0.0750,0.0779,0.9628
44,IA,0.6837,0.6409,0.6135,0.5657,0.0702,0.0752,0.9337
45,AK,0.7213,0.6835,0.6383,0.5909,0.0830,0.0926,0.8965
46,MT,0.7468,0.6758,0.6795,0.5969,0.0673,0.0790,0.8519
47,WY,0.7620,0.7098,0.6805,0.6119,0.0815,0.0979,0.8321
48,WV,0.7442,0.6553,0.6614,0.5520,0.0828,0.1033,0.8017
49,ND,0.7952,0.6466,0.7509,0.5626,0.0443,0.0840,0.5273

In [3]:
print('=== Sex: Summary (4 features) ===')
ratios = full_sex['gap_ratio_g0_g1']
print(f'Median ratio: {ratios.median():.3f}')
print(f'Mean ratio:   {ratios.mean():.3f}')
print(f'Std ratio:    {ratios.std():.3f}')
print(f'Range: [{ratios.min():.3f}, {ratios.max():.3f}]')
print(f'ratio > 1.5:  {(ratios > 1.5).sum()} states: {list(full_sex[ratios > 1.5]["state"])}')
print(f'ratio < 0.67: {(ratios < 0.67).sum()} states: {list(full_sex[ratios < 0.67]["state"])}')
print(f'0.67 <= ratio <= 1.5: {((ratios >= 0.67) & (ratios <= 1.5)).sum()} states')

=== Sex: Summary (4 features) ===
Median ratio: 1.148
Mean ratio:   1.142
Std ratio:    0.177
Range: [0.527, 1.561]
ratio > 1.5:  1 states: ['NH']
ratio < 0.67: 1 states: ['ND']
0.67 <= ratio <= 1.5: 48 states

## Race Binary (White / Non-White)

In [4]:
df_race = pd.read_csv('../oracle_gap_scan_race_binary_employed.csv')
full_race = df_race[df_race['n_features'] == 4].copy()
full_race = full_race.sort_values('gap_ratio_g0_g1', ascending=False)

disp_race = full_race[['state', 'baseline_g0', 'baseline_g1', 'oracle_g0', 'oracle_g1', 'gap_g0', 'gap_g1', 'gap_ratio_g0_g1']].copy()
disp_race.columns = ['State', 'Baseline(W)', 'Baseline(NW)', 'Oracle(W)', 'Oracle(NW)', 'Gap(W)', 'Gap(NW)', 'Ratio(W/NW)']
disp_race = disp_race.reset_index(drop=True)
disp_race

,State,Baseline(W),Baseline(NW),Oracle(W),Oracle(NW),Gap(W),Gap(NW),Ratio(W/NW)
0,HI,0.8061,0.6588,0.7020,0.5980,0.1041,0.0608,1.7126
1,DE,0.7349,0.8070,0.6260,0.7162,0.1090,0.0908,1.2005
2,CA,0.8402,0.8091,0.7082,0.6929,0.1319,0.1161,1.1359
3,ID,0.7458,0.7342,0.6755,0.6723,0.0703,0.0620,1.1347
4,NV,0.7478,0.6979,0.6568,0.6154,0.0910,0.0825,1.1032
5,OK,0.7530,0.6879,0.6852,0.6265,0.0677,0.0614,1.1031
6,TX,0.8071,0.7913,0.6983,0.6903,0.1088,0.1010,1.0769
7,MD,0.7944,0.7644,0.6657,0.6394,0.1286,0.1250,1.0292
8,KY,0.7237,0.7020,0.6362,0.6151,0.0875,0.0870,1.0057
9,RI,0.6913,0.6865,0.5861,0.5811,0.1052,0.1054,0.9985
10,GA,0.7915,0.7648,0.6812,0.6532,0.1103,0.1116,0.9881
11,NM,0.7889,0.7712,0.6835,0.6645,0.1054,0.1067,0.9879
12,TN,0.7403,0.7635,0.6413,0.6613,0.0990,0.1021,0.9693
13,VA,0.7936,0.7964,0.6683,0.6661,0.1254,0.1303,0.9622
14,MS,0.7133,0.6877,0.6222,0.5907,0.0911,0.0970,0.9389
15,AK,0.7052,0.7051,0.6262,0.6207,0.0789,0.0844,0.9347
16,MO,0.7351,0.7260,0.6549,0.6393,0.0802,0.0867,0.9252
17,UT,0.7505,0.7806,0.6456,0.6640,0.1049,0.1166,0.9000
18,IL,0.7628,0.7631,0.6662,0.6550,0.0966,0.1080,0.8937
19,IN,0.6857,0.7276,0.6140,0.6472,0.0717,0.0803,0.8929
20,NC,0.7647,0.7528,0.6657,0.6418,0.0991,0.1110,0.8922
21,NY,0.8013,0.7727,0.7070,0.6669,0.0943,0.1058,0.8911
22,AL,0.7412,0.7284,0.6463,0.6215,0.0948,0.1070,0.8864
23,AZ,0.7399,0.7199,0.6442,0.6119,0.0957,0.1081,0.8857
24,FL,0.7791,0.7570,0.6846,0.6492,0.0946,0.1078,0.8772
25,CO,0.7550,0.7678,0.6689,0.6691,0.0861,0.0988,0.8723
26,WA,0.7465,0.7716,0.6612,0.6720,0.0853,0.0996,0.8558
27,MI,0.7362,0.7714,0.6472,0.6669,0.0890,0.1045,0.8517
28,OR,0.7421,0.7678,0.6497,0.6592,0.0924,0.1086,0.8508
29,NJ,0.7984,0.8212,0.6857,0.6886,0.1128,0.1326,0.8507
30,AR,0.7078,0.6480,0.6341,0.5602,0.0737,0.0878,0.8391
31,PA,0.7161,0.7675,0.6341,0.6682,0.0820,0.0993,0.8255
32,SC,0.7483,0.7185,0.6509,0.5961,0.0975,0.1224,0.7963
33,OH,0.6940,0.7407,0.6053,0.6256,0.0887,0.1151,0.7709
34,MA,0.7535,0.8007,0.6560,0.6652,0.0975,0.1356,0.7194
35,KS,0.7368,0.7857,0.6694,0.6891,0.0674,0.0966,0.6978
36,NE,0.7008,0.7365,0.6427,0.6503,0.0581,0.0863,0.6736
37,LA,0.7585,0.7498,0.6768,0.6277,0.0818,0.1221,0.6696
38,CT,0.7953,0.8448,0.6910,0.6879,0.1043,0.1569,0.6645
39,WI,0.6874,0.7233,0.6308,0.6355,0.0565,0.0878,0.6440
40,IA,0.6561,0.8422,0.6038,0.7594,0.0523,0.0828,0.6313
41,MN,0.7140,0.7237,0.6538,0.6282,0.0602,0.0955,0.6305
42,MT,0.7215,0.6756,0.6698,0.5897,0.0518,0.0859,0.6025
43,VT,0.6888,0.7613,0.6336,0.6628,0.0553,0.0984,0.5613
44,NH,0.7075,0.7888,0.6248,0.6413,0.0826,0.1475,0.5601
45,WV,0.6999,0.8532,0.6354,0.7373,0.0645,0.1159,0.5569
46,WY,0.7307,0.8586,0.6753,0.7557,0.0554,0.1029,0.5388
47,SD,0.7388,0.6286,0.6950,0.5308,0.0437,0.0978,0.4474
48,ME,0.6497,0.7223,0.5831,0.5610,0.0666,0.1613,0.4129
49,ND,0.7436,0.6957,0.7153,0.6063,0.0284,0.0893,0.3175

In [5]:
print('=== Race Binary: Summary (4 features) ===')
ratios_r = full_race['gap_ratio_g0_g1']
print(f'Median ratio: {ratios_r.median():.3f}')
print(f'Mean ratio:   {ratios_r.mean():.3f}')
print(f'Std ratio:    {ratios_r.std():.3f}')
print(f'Range: [{ratios_r.min():.3f}, {ratios_r.max():.3f}]')
print(f'ratio > 1.5:  {(ratios_r > 1.5).sum()} states: {list(full_race[ratios_r > 1.5]["state"])}')
print(f'ratio < 0.67: {(ratios_r < 0.67).sum()} states: {list(full_race[ratios_r < 0.67]["state"])}')
print(f'0.67 <= ratio <= 1.5: {((ratios_r >= 0.67) & (ratios_r <= 1.5)).sum()} states')

=== Race Binary: Summary (4 features) ===
Median ratio: 0.875
Mean ratio:   0.843
Std ratio:    0.236
Range: [0.318, 1.713]
ratio > 1.5:  1 states: ['HI']
ratio < 0.67: 13 states: ['LA', 'CT', 'WI', 'IA', 'MN', 'MT', 'VT', 'NH', 'WV', 'WY', 'SD', 'ME', 'ND']
0.67 <= ratio <= 1.5: 36 states

## Side-by-side comparison (both partitions)

In [ ]:
# Merge both partitions by state
combined = full_sex[['state', 'gap_g0', 'gap_g1', 'gap_ratio_g0_g1']].copy()
combined.columns = ['State', 'Gap_M', 'Gap_F', 'Ratio_sex']

race_cols = full_race[['state', 'gap_g0', 'gap_g1', 'gap_ratio_g0_g1']].copy()
race_cols.columns = ['State', 'Gap_W', 'Gap_NW', 'Ratio_race']

combined = combined.merge(race_cols, on='State')
combined = combined.sort_values('State')
combined = combined.reset_index(drop=True)
combined

## Single-feature summary: sex/MARC vs race/AGEP

In [7]:
# Sex / MARC only
sex_marc = df_sex[(df_sex['n_features'] == 1) & (df_sex['features'] == 'MARC')].copy()
sex_marc = sex_marc.sort_values('gap_ratio_g0_g1', ascending=False)

disp_marc = sex_marc[['state', 'baseline_g0', 'baseline_g1', 'oracle_g0', 'oracle_g1', 'gap_g0', 'gap_g1', 'gap_ratio_g0_g1']].copy()
disp_marc.columns = ['State', 'Baseline(M)', 'Baseline(F)', 'Oracle(M)', 'Oracle(F)', 'Gap(M)', 'Gap(F)', 'Ratio(M/F)']
disp_marc = disp_marc.reset_index(drop=True)

print('=== Sex / MARC: Summary ===')
r_marc = sex_marc['gap_ratio_g0_g1']
print(f'Median ratio: {r_marc.median():.3f}')
print(f'Mean ratio:   {r_marc.mean():.3f}')
print(f'Std ratio:    {r_marc.std():.3f}')
print(f'Range: [{r_marc.min():.3f}, {r_marc.max():.3f}]')
print(f'ratio > 1.5:  {(r_marc > 1.5).sum()} states')
print(f'ratio > 2.0:  {(r_marc > 2.0).sum()} states')
print(f'ratio < 1.0:  {(r_marc < 1.0).sum()} states')
print()
disp_marc

=== Sex / MARC: Summary ===
Median ratio: 1.617
Mean ratio:   1.625
Std ratio:    0.317
Range: [0.709, 2.178]
ratio > 1.5:  34 states
ratio > 2.0:  7 states
ratio < 1.0:  1 states

,State,Baseline(M),Baseline(F),Oracle(M),Oracle(F),Gap(M),Gap(F),Ratio(M/F)
0,VA,0.8314,0.7457,0.7802,0.7222,0.0512,0.0235,2.1780
1,HI,0.7268,0.6549,0.6951,0.6403,0.0317,0.0146,2.1653
2,NV,0.7732,0.6767,0.7444,0.6633,0.0288,0.0134,2.1465
3,MD,0.8138,0.7468,0.7671,0.7247,0.0467,0.0221,2.1133
4,AK,0.7213,0.6835,0.6843,0.6658,0.0369,0.0177,2.0914
5,NY,0.8397,0.7334,0.8144,0.7213,0.0253,0.0122,2.0859
6,AZ,0.7729,0.6841,0.7396,0.6677,0.0332,0.0164,2.0318
7,NJ,0.8461,0.7461,0.7917,0.7185,0.0544,0.0276,1.9722
8,DE,0.7720,0.7283,0.7307,0.7072,0.0413,0.0211,1.9531
9,CA,0.8565,0.7878,0.8241,0.7708,0.0324,0.0171,1.8982
10,OR,0.7707,0.7102,0.7313,0.6894,0.0394,0.0208,1.8965
11,CT,0.8672,0.7137,0.8200,0.6884,0.0472,0.0253,1.8692
12,TN,0.7852,0.6874,0.7434,0.6649,0.0418,0.0226,1.8514
13,NM,0.8175,0.7416,0.7818,0.7222,0.0357,0.0194,1.8371
14,GA,0.8196,0.7349,0.7741,0.7096,0.0455,0.0253,1.7974
15,IL,0.7953,0.7179,0.7537,0.6944,0.0416,0.0234,1.7789
16,MN,0.7394,0.6796,0.7064,0.6608,0.0330,0.0187,1.7599
17,FL,0.8305,0.7008,0.7949,0.6801,0.0356,0.0206,1.7265
18,ME,0.6575,0.6463,0.6260,0.6278,0.0315,0.0185,1.7037
19,OH,0.7259,0.6637,0.6828,0.6383,0.0431,0.0254,1.6990
20,VT,0.6991,0.6815,0.6768,0.6682,0.0223,0.0133,1.6716
21,MO,0.7757,0.6790,0.7383,0.6566,0.0374,0.0224,1.6683
22,RI,0.7275,0.6425,0.6849,0.6165,0.0426,0.0260,1.6385
23,CO,0.7909,0.7070,0.7522,0.6833,0.0386,0.0236,1.6330
24,NC,0.8057,0.7036,0.7641,0.6779,0.0417,0.0257,1.6214
25,MA,0.8002,0.7100,0.7542,0.6814,0.0461,0.0286,1.6121
26,PA,0.7492,0.6832,0.7119,0.6600,0.0373,0.0232,1.6035
27,NE,0.7361,0.6572,0.7043,0.6371,0.0318,0.0200,1.5919
28,SC,0.7871,0.6829,0.7397,0.6531,0.0474,0.0298,1.5917
29,AR,0.7308,0.6564,0.6908,0.6312,0.0400,0.0252,1.5866
30,TX,0.8427,0.7480,0.8013,0.7218,0.0414,0.0262,1.5804
31,MI,0.7845,0.6753,0.7432,0.6488,0.0412,0.0265,1.5540
32,WA,0.7727,0.7218,0.7311,0.6950,0.0416,0.0267,1.5535
33,KY,0.7559,0.6763,0.7213,0.6539,0.0346,0.0224,1.5480
34,NH,0.7283,0.6892,0.6798,0.6563,0.0485,0.0329,1.4727
35,SD,0.7919,0.6429,0.7559,0.6177,0.0360,0.0252,1.4298
36,KS,0.7659,0.7077,0.7213,0.6757,0.0447,0.0319,1.3981
37,WI,0.7222,0.6423,0.6912,0.6197,0.0310,0.0226,1.3710
38,MT,0.7468,0.6758,0.7105,0.6494,0.0362,0.0264,1.3703
39,LA,0.8008,0.6998,0.7490,0.6604,0.0519,0.0394,1.3161
40,AL,0.7806,0.6783,0.7351,0.6435,0.0455,0.0348,1.3075
41,WY,0.7620,0.7098,0.7189,0.6766,0.0431,0.0332,1.2978
42,MS,0.7404,0.6613,0.6961,0.6271,0.0443,0.0342,1.2937
43,IA,0.6837,0.6409,0.6479,0.6132,0.0358,0.0277,1.2916
44,ID,0.7641,0.7128,0.7273,0.6835,0.0368,0.0294,1.2532
45,IN,0.7192,0.6480,0.6791,0.6157,0.0401,0.0323,1.2422
46,OK,0.7714,0.6906,0.7337,0.6593,0.0377,0.0313,1.2028
47,UT,0.7567,0.7489,0.6994,0.6989,0.0573,0.0500,1.1471
48,WV,0.7442,0.6553,0.7086,0.6235,0.0356,0.0318,1.1199
49,ND,0.7952,0.6466,0.7659,0.6053,0.0292,0.0412,0.7089

In [8]:
# Race / AGEP only
race_agep = df_race[(df_race['n_features'] == 1) & (df_race['features'] == 'AGEP')].copy()
race_agep = race_agep.sort_values('gap_ratio_g0_g1', ascending=False)

disp_agep = race_agep[['state', 'baseline_g0', 'baseline_g1', 'oracle_g0', 'oracle_g1', 'gap_g0', 'gap_g1', 'gap_ratio_g0_g1']].copy()
disp_agep.columns = ['State', 'Baseline(W)', 'Baseline(NW)', 'Oracle(W)', 'Oracle(NW)', 'Gap(W)', 'Gap(NW)', 'Ratio(W/NW)']
disp_agep = disp_agep.reset_index(drop=True)

print('=== Race / AGEP: Summary ===')
r_agep = race_agep['gap_ratio_g0_g1']
print(f'Median ratio: {r_agep.median():.3f}')
print(f'Mean ratio:   {r_agep.mean():.3f}')
print(f'Std ratio:    {r_agep.std():.3f}')
print(f'Range: [{r_agep.min():.3f}, {r_agep.max():.3f}]')
print(f'ratio > 1.5:  {(r_agep > 1.5).sum()} states')
print(f'ratio < 0.5:  {(r_agep < 0.5).sum()} states')
print(f'ratio < 0.67: {(r_agep < 0.67).sum()} states')
print()
disp_agep

=== Race / AGEP: Summary ===
Median ratio: 0.610
Mean ratio:   0.734
Std ratio:    0.545
Range: [0.101, 3.481]
ratio > 1.5:  3 states
ratio < 0.5:  15 states
ratio < 0.67: 29 states

,State,Baseline(W),Baseline(NW),Oracle(W),Oracle(NW),Gap(W),Gap(NW),Ratio(W/NW)
0,HI,0.8061,0.6588,0.7338,0.6380,0.0723,0.0208,3.4810
1,CA,0.8402,0.8091,0.8040,0.7922,0.0362,0.0169,2.1391
2,WA,0.7465,0.7716,0.7222,0.7572,0.0243,0.0144,1.6900
3,NJ,0.7984,0.8212,0.7673,0.7973,0.0312,0.0239,1.3061
4,VT,0.6888,0.7613,0.6691,0.7454,0.0198,0.0158,1.2471
5,TX,0.8071,0.7913,0.7787,0.7678,0.0284,0.0235,1.2106
6,VA,0.7936,0.7964,0.7565,0.7598,0.0371,0.0366,1.0141
7,MD,0.7944,0.7644,0.7505,0.7209,0.0439,0.0434,1.0107
8,OR,0.7421,0.7678,0.7136,0.7378,0.0285,0.0299,0.9509
9,OK,0.7530,0.6879,0.7298,0.6632,0.0231,0.0247,0.9343
10,NH,0.7075,0.7888,0.6815,0.7596,0.0260,0.0292,0.8879
11,NY,0.8013,0.7727,0.7796,0.7472,0.0217,0.0255,0.8513
12,GA,0.7915,0.7648,0.7581,0.7236,0.0334,0.0413,0.8090
13,ID,0.7458,0.7342,0.7209,0.7032,0.0249,0.0310,0.8042
14,IL,0.7628,0.7631,0.7395,0.7338,0.0233,0.0292,0.7954
15,AK,0.7052,0.7051,0.6632,0.6517,0.0420,0.0534,0.7868
16,DE,0.7349,0.8070,0.7032,0.7662,0.0318,0.0408,0.7776
17,IN,0.6857,0.7276,0.6626,0.6970,0.0232,0.0306,0.7581
18,NV,0.7478,0.6979,0.7103,0.6476,0.0375,0.0503,0.7452
19,MI,0.7362,0.7714,0.7121,0.7379,0.0241,0.0334,0.7216
20,MA,0.7535,0.8007,0.7290,0.7665,0.0245,0.0343,0.7155
21,NM,0.7889,0.7712,0.7525,0.7165,0.0364,0.0547,0.6658
22,MO,0.7351,0.7260,0.7150,0.6949,0.0201,0.0311,0.6453
23,KY,0.7237,0.7020,0.6975,0.6609,0.0262,0.0411,0.6362
24,MS,0.7133,0.6877,0.6749,0.6250,0.0385,0.0627,0.6135
25,AZ,0.7399,0.7199,0.7101,0.6708,0.0298,0.0492,0.6068
26,CO,0.7550,0.7678,0.7294,0.7244,0.0256,0.0434,0.5895
27,TN,0.7403,0.7635,0.7080,0.7077,0.0323,0.0558,0.5788
28,FL,0.7791,0.7570,0.7488,0.7043,0.0304,0.0527,0.5756
29,NC,0.7647,0.7528,0.7369,0.7039,0.0279,0.0489,0.5705
30,UT,0.7505,0.7806,0.7100,0.7089,0.0405,0.0717,0.5646
31,AL,0.7412,0.7284,0.7053,0.6612,0.0358,0.0672,0.5327
32,PA,0.7161,0.7675,0.6973,0.7321,0.0188,0.0354,0.5309
33,OH,0.6940,0.7407,0.6686,0.6928,0.0254,0.0479,0.5293
34,CT,0.7953,0.8448,0.7652,0.7864,0.0301,0.0584,0.5151
35,AR,0.7078,0.6480,0.6853,0.6028,0.0225,0.0452,0.4983
36,RI,0.6913,0.6865,0.6540,0.6087,0.0373,0.0779,0.4790
37,NE,0.7008,0.7365,0.6843,0.6998,0.0166,0.0368,0.4508
38,SC,0.7483,0.7185,0.7145,0.6370,0.0339,0.0815,0.4154
39,KS,0.7368,0.7857,0.7171,0.7383,0.0197,0.0474,0.4149
40,LA,0.7585,0.7498,0.7274,0.6714,0.0311,0.0784,0.3969
41,WI,0.6874,0.7233,0.6741,0.6835,0.0132,0.0398,0.3321
42,WY,0.7307,0.8586,0.7064,0.7802,0.0243,0.0784,0.3105
43,WV,0.6999,0.8532,0.6851,0.8023,0.0149,0.0509,0.2926
44,MT,0.7215,0.6756,0.7058,0.6215,0.0157,0.0541,0.2909
45,ME,0.6497,0.7223,0.6280,0.6407,0.0217,0.0816,0.2655
46,IA,0.6561,0.8422,0.6416,0.7843,0.0145,0.0579,0.2504
47,MN,0.7140,0.7237,0.7030,0.6747,0.0110,0.0490,0.2240
48,SD,0.7388,0.6286,0.7246,0.5502,0.0142,0.0784,0.1814
49,ND,0.7436,0.6957,0.7361,0.6208,0.0076,0.0749,0.1010

In [9]:
# Side-by-side: sex/MARC vs race/AGEP
single_combined = sex_marc[['state', 'gap_g0', 'gap_g1', 'gap_ratio_g0_g1']].copy()
single_combined.columns = ['State', 'Gap_M(MARC)', 'Gap_F(MARC)', 'Ratio_sex_MARC']

agep_cols = race_agep[['state', 'gap_g0', 'gap_g1', 'gap_ratio_g0_g1']].copy()
agep_cols.columns = ['State', 'Gap_W(AGEP)', 'Gap_NW(AGEP)', 'Ratio_race_AGEP']

single_combined = single_combined.merge(agep_cols, on='State')
single_combined = single_combined.sort_values('State').reset_index(drop=True)
single_combined

,State,Gap_M(MARC),Gap_F(MARC),Ratio_sex_MARC,Gap_W(AGEP),Gap_NW(AGEP),Ratio_race_AGEP
0,AK,0.0369,0.0177,2.0914,0.0420,0.0534,0.7868
1,AL,0.0455,0.0348,1.3075,0.0358,0.0672,0.5327
2,AR,0.0400,0.0252,1.5866,0.0225,0.0452,0.4983
3,AZ,0.0332,0.0164,2.0318,0.0298,0.0492,0.6068
4,CA,0.0324,0.0171,1.8982,0.0362,0.0169,2.1391
5,CO,0.0386,0.0236,1.6330,0.0256,0.0434,0.5895
6,CT,0.0472,0.0253,1.8692,0.0301,0.0584,0.5151
7,DE,0.0413,0.0211,1.9531,0.0318,0.0408,0.7776
8,FL,0.0356,0.0206,1.7265,0.0304,0.0527,0.5756
9,GA,0.0455,0.0253,1.7974,0.0334,0.0413,0.8090
10,HI,0.0317,0.0146,2.1653,0.0723,0.0208,3.4810
11,IA,0.0358,0.0277,1.2916,0.0145,0.0579,0.2504
12,ID,0.0368,0.0294,1.2532,0.0249,0.0310,0.8042
13,IL,0.0416,0.0234,1.7789,0.0233,0.0292,0.7954
14,IN,0.0401,0.0323,1.2422,0.0232,0.0306,0.7581
15,KS,0.0447,0.0319,1.3981,0.0197,0.0474,0.4149
16,KY,0.0346,0.0224,1.5480,0.0262,0.0411,0.6362
17,LA,0.0519,0.0394,1.3161,0.0311,0.0784,0.3969
18,MA,0.0461,0.0286,1.6121,0.0245,0.0343,0.7155
19,MD,0.0467,0.0221,2.1133,0.0439,0.0434,1.0107
20,ME,0.0315,0.0185,1.7037,0.0217,0.0816,0.2655
21,MI,0.0412,0.0265,1.5540,0.0241,0.0334,0.7216
22,MN,0.0330,0.0187,1.7599,0.0110,0.0490,0.2240
23,MO,0.0374,0.0224,1.6683,0.0201,0.0311,0.6453
24,MS,0.0443,0.0342,1.2937,0.0385,0.0627,0.6135
25,MT,0.0362,0.0264,1.3703,0.0157,0.0541,0.2909
26,NC,0.0417,0.0257,1.6214,0.0279,0.0489,0.5705
27,ND,0.0292,0.0412,0.7089,0.0076,0.0749,0.1010
28,NE,0.0318,0.0200,1.5919,0.0166,0.0368,0.4508
29,NH,0.0485,0.0329,1.4727,0.0260,0.0292,0.8879
30,NJ,0.0544,0.0276,1.9722,0.0312,0.0239,1.3061
31,NM,0.0357,0.0194,1.8371,0.0364,0.0547,0.6658
32,NV,0.0288,0.0134,2.1465,0.0375,0.0503,0.7452
33,NY,0.0253,0.0122,2.0859,0.0217,0.0255,0.8513
34,OH,0.0431,0.0254,1.6990,0.0254,0.0479,0.5293
35,OK,0.0377,0.0313,1.2028,0.0231,0.0247,0.9343
36,OR,0.0394,0.0208,1.8965,0.0285,0.0299,0.9509
37,PA,0.0373,0.0232,1.6035,0.0188,0.0354,0.5309
38,RI,0.0426,0.0260,1.6385,0.0373,0.0779,0.4790
39,SC,0.0474,0.0298,1.5917,0.0339,0.0815,0.4154
40,SD,0.0360,0.0252,1.4298,0.0142,0.0784,0.1814
41,TN,0.0418,0.0226,1.8514,0.0323,0.0558,0.5788
42,TX,0.0414,0.0262,1.5804,0.0284,0.0235,1.2106
43,UT,0.0573,0.0500,1.1471,0.0405,0.0717,0.5646
44,VA,0.0512,0.0235,2.1780,0.0371,0.0366,1.0141
45,VT,0.0223,0.0133,1.6716,0.0198,0.0158,1.2471
46,WA,0.0416,0.0267,1.5535,0.0243,0.0144,1.6900
47,WI,0.0310,0.0226,1.3710,0.0132,0.0398,0.3321
48,WV,0.0356,0.0318,1.1199,0.0149,0.0509,0.2926
49,WY,0.0431,0.0332,1.2978,0.0243,0.0784,0.3105

## Intro examples: ND, CA, HI

Per-state Pareto frontier results from `intro_diff_scale_*_employed.ipynb`.
Single-feature (MARC for sex, AGEP for race) + full 4-feature models.

In [10]:
import importlib, warnings
from sklearn.preprocessing import StandardScaler
warnings.filterwarnings('ignore')

import folktables_utils, train_methods
importlib.reload(folktables_utils)
importlib.reload(train_methods)

from folktables_utils import load_acs_income
from train_methods import (
    solve_weighted_groups_closed_form,
    train_group_oracles,
    compute_baseline_losses,
)

YEAR = 2018
NUM_LAMBDAS = 10001
lambdas = np.linspace(0, 1, NUM_LAMBDAS)
METHODS_LIST = ['ERM', 'GDRO', 'MMR', 'MMRI', 'MMV', 'Nash']

In [11]:
def run_config(state, group_by, features, g0_name, g1_name):
    """Run Pareto frontier + all methods for one configuration."""
    X, y, g, num_groups, _ = load_acs_income(
        states=(state,), year=YEAR, group_by=group_by,
        features=features, employed_only=True
    )
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    baseline = compute_baseline_losses(y, g, num_groups)
    oracle = train_group_oracles(X_scaled, y, g, num_groups=num_groups, closed_form=True, verbose=False)
    gap = baseline - oracle
    
    # Pareto frontier
    cp = np.array([
        solve_weighted_groups_closed_form(X_scaled, y, g, num_groups, lam)[2]
        for lam in lambdas
    ])
    
    # Method solutions
    n1 = (g == 1).sum()
    erm_lam = n1 / len(g)
    erm_idx = np.argmin(np.abs(lambdas - erm_lam))
    dro_idx = np.argmin(cp.max(axis=1))
    regrets = cp - oracle[np.newaxis, :]
    mmr_idx = np.argmin(regrets.max(axis=1))
    ri = (baseline[np.newaxis, :] - cp) / gap[np.newaxis, :]
    mri_idx = np.argmax(ri.min(axis=1))
    surplus = baseline[np.newaxis, :] - cp
    nash_prod = np.prod(surplus, axis=1)
    nash_prod[~np.all(surplus > 0, axis=1)] = -np.inf
    nash_idx = np.argmax(nash_prod)
    mmv_val = surplus.copy()
    mmv_val[~np.all(surplus > 0, axis=1)] = -np.inf
    mmv_idx = np.argmax(mmv_val.min(axis=1))
    
    methods = {
        'ERM': cp[erm_idx], 'GDRO': cp[dro_idx], 'MMR': cp[mmr_idx],
        'MMRI': cp[mri_idx], 'Nash': cp[nash_idx], 'MMV': cp[mmv_idx],
    }
    
    # Build result rows
    rows = []
    for name in METHODS_LIST:
        r = methods[name]
        ri_g0 = (baseline[0] - r[0]) / gap[0] if gap[0] > 1e-10 else 0
        ri_g1 = (baseline[1] - r[1]) / gap[1] if gap[1] > 1e-10 else 0
        rows.append({
            'Method': name,
            f'RMSE({g0_name})': r[0],
            f'RMSE({g1_name})': r[1],
            f'RI({g0_name})': ri_g0,
            f'RI({g1_name})': ri_g1,
            'min_RI': min(ri_g0, ri_g1),
            'RI_gap': abs(ri_g0 - ri_g1),
        })
    
    result_df = pd.DataFrame(rows)
    
    feat_str = ','.join(features)
    ratio = gap[0] / gap[1] if gap[1] > 1e-10 else np.inf
    
    print(f"\n{'='*70}")
    print(f"{state} / {group_by} / {feat_str}")
    print(f"  n={len(y)}, {g0_name}={(g==0).sum()}, {g1_name}={(g==1).sum()}")
    print(f"  Baseline: {g0_name}={baseline[0]:.4f}, {g1_name}={baseline[1]:.4f}")
    print(f"  Oracle:   {g0_name}={oracle[0]:.4f}, {g1_name}={oracle[1]:.4f}")
    print(f"  Gap:      {g0_name}={gap[0]:.4f}, {g1_name}={gap[1]:.4f}")
    print(f"  Gap ratio ({g0_name}/{g1_name}): {ratio:.3f}")
    print(f"{'='*70}")
    
    return result_df, {'state': state, 'group_by': group_by, 'features': feat_str,
                       'gap_ratio': ratio, 'gap_g0': gap[0], 'gap_g1': gap[1],
                       'baseline_g0': baseline[0], 'baseline_g1': baseline[1],
                       'oracle_g0': oracle[0], 'oracle_g1': oracle[1]}

In [12]:
# ====== Run all intro configurations ======
FULL_FEATURES = ["AGEP", "SCHL", "MARC", "RELPC"]

configs = [
    # (state, group_by, features, g0_name, g1_name, label)
    ("ND", "sex",         ["MARC"], "Male", "Female",    "ND/sex/MARC"),
    ("ND", "race_binary", ["AGEP"], "White", "Non-White", "ND/race/AGEP"),
    ("CA", "sex",         ["MARC"], "Male", "Female",    "CA/sex/MARC"),
    ("CA", "race_binary", ["AGEP"], "White", "Non-White", "CA/race/AGEP"),
    ("HI", "sex",         ["MARC"], "Male", "Female",    "HI/sex/MARC"),
    ("HI", "race_binary", ["AGEP"], "White", "Non-White", "HI/race/AGEP"),
    # Full features
    ("ND", "sex",         FULL_FEATURES, "Male", "Female",    "ND/sex/all4"),
    ("ND", "race_binary", FULL_FEATURES, "White", "Non-White", "ND/race/all4"),
    ("CA", "sex",         FULL_FEATURES, "Male", "Female",    "CA/sex/all4"),
    ("CA", "race_binary", FULL_FEATURES, "White", "Non-White", "CA/race/all4"),
    ("HI", "sex",         FULL_FEATURES, "Male", "Female",    "HI/sex/all4"),
    ("HI", "race_binary", FULL_FEATURES, "White", "Non-White", "HI/race/all4"),
]

all_results = {}
all_meta = []

for state, gb, feats, g0, g1, label in configs:
    df_res, meta = run_config(state, gb, feats, g0, g1)
    all_results[label] = df_res
    meta['label'] = label
    all_meta.append(meta)

Removed 3370 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 4506 -> 2785
Removed 5 samples with non-positive income
Selected 1 features: ['MARC']
Loaded 2780 samples, 1 features, 2 groups (group_by=sex)

======================================================================
ND / sex / MARC
  n=2780, Male=1676, Female=1104
  Baseline: Male=0.7952, Female=0.6466
  Oracle:   Male=0.7659, Female=0.6053
  Gap:      Male=0.0292, Female=0.0412
  Gap ratio (Male/Female): 0.709
======================================================================
Removed 3370 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 4506 -> 2785
Removed 5 samples with non-positive income
Selected 1 features: ['AGEP']
Loaded 2780 samples, 1 features, 2 groups (group_by=race_binary)

======================================================================
ND / race_binary / AGEP
  n=2780, White=2549, Non-White=231
  Baseline: White=0.7436, Non-White=0.6957
  Oracle:   White=0.7361, Non-White=0.6208
  Gap:      White=0.0076, Non-White=0.0749
  Gap ratio (White/Non-White): 0.101
======================================================================
Removed 182213 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 196604 -> 118073
Removed 76 samples with non-positive income
Selected 1 features: ['MARC']
Loaded 117997 samples, 1 features, 2 groups (group_by=sex)

======================================================================
CA / sex / MARC
  n=117997, Male=68376, Female=49621
  Baseline: Male=0.8565, Female=0.7878
  Oracle:   Male=0.8241, Female=0.7708
  Gap:      Male=0.0324, Female=0.0171
  Gap ratio (Male/Female): 1.898
======================================================================
Removed 182213 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 196604 -> 118073
Removed 76 samples with non-positive income
Selected 1 features: ['AGEP']
Loaded 117997 samples, 1 features, 2 groups (group_by=race_binary)

======================================================================
CA / race_binary / AGEP
  n=117997, White=72584, Non-White=45413
  Baseline: White=0.8402, Non-White=0.8091
  Oracle:   White=0.8040, Non-White=0.7922
  Gap:      White=0.0362, Non-White=0.0169
  Gap ratio (White/Non-White): 2.139
======================================================================
Removed 6631 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 7769 -> 4669
Removed 2 samples with non-positive income
Selected 1 features: ['MARC']
Loaded 4667 samples, 1 features, 2 groups (group_by=sex)

======================================================================
HI / sex / MARC
  n=4667, Male=2513, Female=2154
  Baseline: Male=0.7268, Female=0.6549
  Oracle:   Male=0.6951, Female=0.6403
  Gap:      Male=0.0317, Female=0.0146
  Gap ratio (Male/Female): 2.165
======================================================================
Removed 6631 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 7769 -> 4669
Removed 2 samples with non-positive income
Selected 1 features: ['AGEP']
Loaded 4667 samples, 1 features, 2 groups (group_by=race_binary)

======================================================================
HI / race_binary / AGEP
  n=4667, White=1046, Non-White=3621
  Baseline: White=0.8061, Non-White=0.6588
  Oracle:   White=0.7338, Non-White=0.6380
  Gap:      White=0.0723, Non-White=0.0208
  Gap ratio (White/Non-White): 3.481
======================================================================
Removed 3370 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 4506 -> 2785
Removed 5 samples with non-positive income
Selected 4 features: ['AGEP', 'SCHL', 'MARC', 'RELPC']
Loaded 2780 samples, 4 features, 2 groups (group_by=sex)

======================================================================
ND / sex / AGEP,SCHL,MARC,RELPC
  n=2780, Male=1676, Female=1104
  Baseline: Male=0.7952, Female=0.6466
  Oracle:   Male=0.7509, Female=0.5626
  Gap:      Male=0.0443, Female=0.0840
  Gap ratio (Male/Female): 0.527
======================================================================
Removed 3370 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 4506 -> 2785
Removed 5 samples with non-positive income
Selected 4 features: ['AGEP', 'SCHL', 'MARC', 'RELPC']
Loaded 2780 samples, 4 features, 2 groups (group_by=race_binary)

======================================================================
ND / race_binary / AGEP,SCHL,MARC,RELPC
  n=2780, White=2549, Non-White=231
  Baseline: White=0.7436, Non-White=0.6957
  Oracle:   White=0.7153, Non-White=0.6063
  Gap:      White=0.0284, Non-White=0.0893
  Gap ratio (White/Non-White): 0.318
======================================================================
Removed 182213 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 196604 -> 118073
Removed 76 samples with non-positive income
Selected 4 features: ['AGEP', 'SCHL', 'MARC', 'RELPC']
Loaded 117997 samples, 4 features, 2 groups (group_by=sex)

======================================================================
CA / sex / AGEP,SCHL,MARC,RELPC
  n=117997, Male=68376, Female=49621
  Baseline: Male=0.8565, Female=0.7878
  Oracle:   Male=0.7141, Female=0.6711
  Gap:      Male=0.1424, Female=0.1167
  Gap ratio (Male/Female): 1.220
======================================================================
Removed 182213 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 196604 -> 118073
Removed 76 samples with non-positive income
Selected 4 features: ['AGEP', 'SCHL', 'MARC', 'RELPC']
Loaded 117997 samples, 4 features, 2 groups (group_by=race_binary)

======================================================================
CA / race_binary / AGEP,SCHL,MARC,RELPC
  n=117997, White=72584, Non-White=45413
  Baseline: White=0.8402, Non-White=0.8091
  Oracle:   White=0.7082, Non-White=0.6929
  Gap:      White=0.1319, Non-White=0.1161
  Gap ratio (White/Non-White): 1.136
======================================================================
Removed 6631 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 7769 -> 4669
Removed 2 samples with non-positive income
Selected 4 features: ['AGEP', 'SCHL', 'MARC', 'RELPC']
Loaded 4667 samples, 4 features, 2 groups (group_by=sex)

======================================================================
HI / sex / AGEP,SCHL,MARC,RELPC
  n=4667, Male=2513, Female=2154
  Baseline: Male=0.7268, Female=0.6549
  Oracle:   Male=0.6395, Female=0.5925
  Gap:      Male=0.0873, Female=0.0625
  Gap ratio (Male/Female): 1.397
======================================================================
Removed 6631 samples with NaN values
Filtered to full-time year-round employed (ESR==1, WKHP>=35, WKW==1): 7769 -> 4669
Removed 2 samples with non-positive income
Selected 4 features: ['AGEP', 'SCHL', 'MARC', 'RELPC']
Loaded 4667 samples, 4 features, 2 groups (group_by=race_binary)

======================================================================
HI / race_binary / AGEP,SCHL,MARC,RELPC
  n=4667, White=1046, Non-White=3621
  Baseline: White=0.8061, Non-White=0.6588
  Oracle:   White=0.7020, Non-White=0.5980
  Gap:      White=0.1041, Non-White=0.0608
  Gap ratio (White/Non-White): 1.713
======================================================================

In [13]:
# ====== Gap ratio overview ======
meta_df = pd.DataFrame(all_meta)[['label', 'state', 'group_by', 'features', 'gap_g0', 'gap_g1', 'gap_ratio']]
meta_df.columns = ['Config', 'State', 'Group', 'Features', 'Gap(G0)', 'Gap(G1)', 'Ratio']
print("Oracle gap ratios across intro configurations:")
meta_df

Oracle gap ratios across intro configurations:

,Config,State,Group,Features,Gap(G0),Gap(G1),Ratio
0,ND/sex/MARC,ND,sex,MARC,0.0292,0.0412,0.7089
1,ND/race/AGEP,ND,race_binary,AGEP,0.0076,0.0749,0.1010
2,CA/sex/MARC,CA,sex,MARC,0.0324,0.0171,1.8982
3,CA/race/AGEP,CA,race_binary,AGEP,0.0362,0.0169,2.1391
4,HI/sex/MARC,HI,sex,MARC,0.0317,0.0146,2.1653
5,HI/race/AGEP,HI,race_binary,AGEP,0.0723,0.0208,3.4810
6,ND/sex/all4,ND,sex,"AGEP,SCHL,MARC,RELPC",0.0443,0.0840,0.5273
7,ND/race/all4,ND,race_binary,"AGEP,SCHL,MARC,RELPC",0.0284,0.0893,0.3175
8,CA/sex/all4,CA,sex,"AGEP,SCHL,MARC,RELPC",0.1424,0.1167,1.2200
9,CA/race/all4,CA,race_binary,"AGEP,SCHL,MARC,RELPC",0.1319,0.1161,1.1359
10,HI/sex/all4,HI,sex,"AGEP,SCHL,MARC,RELPC",0.0873,0.0625,1.3972
11,HI/race/all4,HI,race_binary,"AGEP,SCHL,MARC,RELPC",0.1041,0.0608,1.7126

In [14]:
# ====== Method RI comparison across all configs ======
summary_rows = []
for label, df_res in all_results.items():
    for _, row in df_res.iterrows():
        summary_rows.append({
            'Config': label,
            'Method': row['Method'],
            'min_RI': row['min_RI'],
            'RI_gap': row['RI_gap'],
        })

ri_summary = pd.DataFrame(summary_rows)
ri_pivot = ri_summary.pivot_table(index='Config', columns='Method', values='min_RI')
ri_pivot = ri_pivot[METHODS_LIST]

print("min-group RI by method (higher = better):")
ri_pivot.style.format("{:.2%}").background_gradient(cmap='RdYlGn', axis=None)

min-group RI by method (higher = better):

In [15]:
# ====== RI gap (|RI_g0 - RI_g1|) by method (lower = more balanced) ======
gap_pivot = ri_summary.pivot_table(index='Config', columns='Method', values='RI_gap')
gap_pivot = gap_pivot[METHODS_LIST]

print("RI gap |ρ₀ - ρ₁| by method (lower = more balanced):")
gap_pivot.style.format("{:.2%}").background_gradient(cmap='RdYlGn_r', axis=None)

RI gap |ρ₀ - ρ₁| by method (lower = more balanced):

In [16]:
# ====== Per-config detailed tables ======
for label in all_results:
    print(f"\n--- {label} ---")
    display(all_results[label].style.format({
        col: "{:.4f}" if 'RMSE' in col else "{:.2%}" 
        for col in all_results[label].columns if col != 'Method'
    }))

--- ND/sex/MARC ---

--- ND/race/AGEP ---

--- CA/sex/MARC ---

--- CA/race/AGEP ---

--- HI/sex/MARC ---

--- HI/race/AGEP ---

--- ND/sex/all4 ---

--- ND/race/all4 ---

--- CA/sex/all4 ---

--- CA/race/all4 ---

--- HI/sex/all4 ---

--- HI/race/all4 ---

In [17]:
# ====== Comprehensive gap ratio distribution analysis ======
# Single-feature models across all 50 states × 2 partitions × 4 features

features_list = ['AGEP', 'SCHL', 'MARC', 'RELPC']

all_single_rows = []

for gb, g0n, g1n in [('sex', 'Male', 'Female'), ('race_binary', 'White', 'Non-White')]:
    df = pd.read_csv(f'../oracle_gap_scan_{gb}_employed.csv')
    for feat in features_list:
        feat_df = df[(df['n_features'] == 1) & (df['features'] == feat)]
        for _, r in feat_df.iterrows():
            all_single_rows.append({
                'state': r['state'],
                'group_by': gb,
                'feature': feat,
                'gap_g0': r['gap_g0'],
                'gap_g1': r['gap_g1'],
                'ratio': r['gap_ratio_g0_g1'],
                'baseline_g0': r['baseline_g0'],
                'baseline_g1': r['baseline_g1'],
                'oracle_g0': r['oracle_g0'],
                'oracle_g1': r['oracle_g1'],
            })

all_single = pd.DataFrame(all_single_rows)
print(f"Total single-feature configurations: {len(all_single)}")
print(f"  = 50 states × 2 partitions × 4 features = {50*2*4}")

Total single-feature configurations: 400
  = 50 states × 2 partitions × 4 features = 400

## Gap ratio distribution summary

ACS Income 2018, folktables, full-time employees (ESR=1, WKHP≥35, WKW=1).

- Features: AGEP, SCHL, MARC (MAR==1), RELPC (RELP==0)
- Groups: sex binary (SEX==1 vs SEX==2), race binary (RAC1P==1 vs RAC1P≠1)
- Oracle gap = R_g(f0) - R_g(f_g*), where f0 = constant predictor (overall mean), f_g* = group-specific OLS
- Gap ratio = oracle_gap_0 / oracle_gap_1

In [18]:
# ====== Distribution summary by (partition × feature) ======

summary_rows = []

for gb in ['sex', 'race_binary']:
    for feat in features_list:
        subset = all_single[(all_single['group_by'] == gb) & (all_single['feature'] == feat)]
        ratios = subset['ratio']
        n = len(ratios)
        
        n_extreme = ((ratios < 0.5) | (ratios > 2.0)).sum()
        n_symmetric = ((ratios >= 0.8) & (ratios <= 1.25)).sum()
        
        summary_rows.append({
            'Partition': gb,
            'Feature': feat,
            'Min': ratios.min(),
            'Median': ratios.median(),
            'Max': ratios.max(),
            'Extreme (r<0.5 or r>2)': f'{n_extreme}/{n} ({100*n_extreme/n:.0f}%)',
            'Symmetric (0.8≤r≤1.25)': f'{n_symmetric}/{n} ({100*n_symmetric/n:.0f}%)',
        })
    
    # Also add "ALL features" row (aggregated)
    subset_all = all_single[all_single['group_by'] == gb]
    ratios_all = subset_all['ratio']
    n_all = len(ratios_all)
    n_ext_all = ((ratios_all < 0.5) | (ratios_all > 2.0)).sum()
    n_sym_all = ((ratios_all >= 0.8) & (ratios_all <= 1.25)).sum()
    summary_rows.append({
        'Partition': gb,
        'Feature': 'ALL',
        'Min': ratios_all.min(),
        'Median': ratios_all.median(),
        'Max': ratios_all.max(),
        'Extreme (r<0.5 or r>2)': f'{n_ext_all}/{n_all} ({100*n_ext_all/n_all:.0f}%)',
        'Symmetric (0.8≤r≤1.25)': f'{n_sym_all}/{n_all} ({100*n_sym_all/n_all:.0f}%)',
    })

summary_df = pd.DataFrame(summary_rows)
print("Gap ratio distribution: single-feature models, 50 states")
print("=" * 90)
summary_df

Gap ratio distribution: single-feature models, 50 states
==========================================================================================

,Partition,Feature,Min,Median,Max,Extreme (r<0.5 or r>2),Symmetric (0.8≤r≤1.25)
0,sex,AGEP,0.5789,1.3169,2.0230,1/50 (2%),19/50 (38%)
1,sex,SCHL,0.3256,0.8756,1.3135,2/50 (4%),33/50 (66%)
2,sex,MARC,0.7089,1.6168,2.1780,7/50 (14%),4/50 (8%)
3,sex,RELPC,0.3651,1.0057,1.8071,3/50 (6%),26/50 (52%)
4,sex,ALL,0.3256,1.1347,2.1780,13/200 (6%),82/200 (41%)
5,race_binary,AGEP,0.1010,0.6102,3.4810,17/50 (34%),10/50 (20%)
6,race_binary,SCHL,0.1453,0.6932,1.8387,6/50 (12%),12/50 (24%)
7,race_binary,MARC,0.1772,0.5279,2.9572,25/50 (50%),4/50 (8%)
8,race_binary,RELPC,0.0424,0.2964,2.8511,43/50 (86%),0/50 (0%)
9,race_binary,ALL,0.0424,0.5407,3.4810,91/200 (46%),26/200 (13%)

In [19]:
# ====== Overall distribution (all partitions × features pooled) ======
all_ratios = all_single['ratio']
n_total = len(all_ratios)

print("=" * 60)
print(f"OVERALL: {n_total} configurations (50 states × 2 partitions × 4 features)")
print("=" * 60)
print(f"Range:     [{all_ratios.min():.3f}, {all_ratios.max():.3f}]")
print(f"Median:    {all_ratios.median():.3f}")
print(f"Mean:      {all_ratios.mean():.3f}")
print(f"Std:       {all_ratios.std():.3f}")
print()

n_ext = ((all_ratios < 0.5) | (all_ratios > 2.0)).sum()
n_sym = ((all_ratios >= 0.8) & (all_ratios <= 1.25)).sum()
n_mod = n_total - n_ext - n_sym  # moderate asymmetry

print(f"Extreme asymmetry (r < 0.5 or r > 2.0):  {n_ext}/{n_total} ({100*n_ext/n_total:.1f}%)")
print(f"Moderate asymmetry:                       {n_mod}/{n_total} ({100*n_mod/n_total:.1f}%)")
print(f"Near-symmetric (0.8 ≤ r ≤ 1.25):          {n_sym}/{n_total} ({100*n_sym/n_total:.1f}%)")
print()
print("→ In the majority of configurations, groups differ substantially in predictability.")

============================================================
OVERALL: 400 configurations (50 states × 2 partitions × 4 features)
============================================================
Range:     [0.042, 3.481]
Median:    0.803
Mean:      0.889
Std:       0.511

Extreme asymmetry (r < 0.5 or r > 2.0):  104/400 (26.0%)
Moderate asymmetry:                       188/400 (47.0%)
Near-symmetric (0.8 ≤ r ≤ 1.25):          108/400 (27.0%)

→ In the majority of configurations, groups differ substantially in predictability.

In [20]:
# ====== Verification: CA/sex/MARC ======
ca_sex_marc = all_single[
    (all_single['state'] == 'CA') & 
    (all_single['group_by'] == 'sex') & 
    (all_single['feature'] == 'MARC')
].iloc[0]

print("Verification: CA / sex / MARC")
print("=" * 50)
print(f"Gap ratio: {ca_sex_marc['ratio']:.3f}  (expected ≈ 1.90)")
print(f"Gap (Male):   {ca_sex_marc['gap_g0']:.4f}")
print(f"Gap (Female): {ca_sex_marc['gap_g1']:.4f}")
print(f"Baseline: Male={ca_sex_marc['baseline_g0']:.4f}, Female={ca_sex_marc['baseline_g1']:.4f}")
print(f"Oracle:   Male={ca_sex_marc['oracle_g0']:.4f}, Female={ca_sex_marc['oracle_g1']:.4f}")

Verification: CA / sex / MARC
==================================================
Gap ratio: 1.898  (expected ≈ 1.90)
Gap (Male):   0.0324
Gap (Female): 0.0171
Baseline: Male=0.8565, Female=0.7878
Oracle:   Male=0.8241, Female=0.7708